POST localhost:8080/auth/register
Content-Type: application/json

{
    "username": "abdulla",
    "password": "pentagool",
    "email": "abdulla.ermatov0407@gmail.com"
}

###
POST localhost:8080/auth/login
Content-Type: application/json

{
    "username": "cricketUser",
    "password": "qwerty123456"
}

###
GET localhost:8080/match/current/1