POST localhost:8080/auth/register
Content-Type: application/json

{
    "username": "newUser",
    "password": "qwerty1234567",
    "email": "new.user46@gmail.com"
}

###
POST localhost:8080/auth/login
Content-Type: application/json

{
    "username": "cricketUserasd",
    "password": "qwerty123456"
}

###
GET localhost:8080/match/current/1